oprofile-tests update error handling around ocount calls
Update the expect script to handle (and return with an error
message)  when ocount returns an
 "Unable to obtain cpu_type" error message/string.

Subsequently turns this confusing output:
  ERROR: tcl error sourcing ./oprofile-ocount/ocount-run.exp.
  ERROR: invalid bareword "to"
  in expression "to * 2";
into this easier to understand blurb:
  ERROR: Ocount failed to obtain a valid cpu_type.

While in the neighborhood, also did a few cosmetic touch-ups.

Tested on ppc64/ppc64le/x86_64.

Signed-off-by:  Will Schmidt <will_schmidt@vnet.ibm.com>